Fix #619: Remove ports from shared YouTube links
yattee/yattee pull request #627
Opened 2024-03-19 15:37 UTC by 0x000C

Issue #619 describes how when the app is connected to a frontend hosted on a non-standard port, that port gets added to shared YouTube links.

This change removes ports from shared YouTube links.

2024-03-19 16:04 UTC, stonerl commented
To me this looks more like a workaround. It seems that the frontendHost gets constructed with the e.g. the invidious instance and only the url part is changed to YouTube afterwards.

A better solution would be to construct the frontendHost correctly in the first place.

Just my 2 cents, though …

2024-03-21 03:41 UTC, 0x000C commented
I updated the shareURL function and it's caller to handle schemas and ports correctly, and more generically than before.

It no longer always uses the active instance's schema and port to form the shared URL, and instead can receive and parse a URL string for that information.

2024-04-01 21:19 UTC, arekf requested changes
Thanks, could you please take care of small style changes to not to use explicit types when possible?

2024-04-01 21:19 UTC, arekf commented on Model/Applications/VideosAPI.swift
> +            urlComponents = URLComponents(URL: frontendURL, resolvingAgainstBaseURL: false)
```suggestion
    func shareURL(_ item: ContentItem, frontendURLString: String? = nil, time: CMTime? = nil) -> URL? {
        var urlComponents: URLComponents?
        if let frontendURLString,
            let frontendURL = URL(string: frontendURLString) {
            urlComponents = URLComponents(URL: frontendURL, resolvingAgainstBaseURL: false)
```

2024-04-01 21:19 UTC, arekf commented on Model/Applications/VideosAPI.swift
> +        guard var urlComponents: URLComponents = urlComponents else {
```suggestion
        guard var urlComponents else {
```

2024-05-16 16:25 UTC, merged